language: node_js
node_js:
  - "10"
sudo: enabled
dist: xenial
install:
  - sudo apt-get clean
  - sudo apt-get update
  - sudo apt-get -y install libxml2-utils
script:
  - chmod +x ./run.sh
  - ./run.sh
